obstacle_segmentation_node:
    ros__parameters:
        input_cloud_topic: "/livox/lidar_PointCloud2"
        output_cloud_topic: "/cloud_obstacle"
        use_downsample: false # 是否使用体素滤波器
        leaf_size: 0.1 # 体素滤波器的体素大小
        point_num_for_normal: 10 # 用于计算法向量的点的数量
        angle_threshold: 0.785 # 法向量与地面夹角的角度阈值(绝对值、弧度制)
        obstacle_x_min: -100.0 # 障碍物的x最小值(livox坐标系)
        obstacle_x_max: 100.0 # 障碍物的x最大值(livox坐标系)
        obstacle_y_min: -100.0 # 障碍物的y最小值(livox坐标系)
        obstacle_y_max: 100.0 # 障碍物的y最大值(livox坐标系)
        obstacle_z_min: -0.5 # 障碍物的z最小值(livox坐标系)
        obstacle_z_max: 0.2 # 障碍物的z最大值(livox坐标系)
        obstacle_range_min: 0.8 # 障碍物的最小距离(livox坐标系)
        obstacle_range_max: 100.0 # 障碍物的最大距离(livox坐标系)
        point_frame: "livox"


